Project telemetry_metrics {
  database_type: 'MariaDB'
  Note: 'Telemetry Metrics'
}

Table telemetry_metric_sample {
  id char(36) [primary key]
  service_id char(36)
  timestamp datetime
  value double
}

Table telemetry_service {
  id char(36) [primary key]
  system_id char(36)
  category_id char(36)
  name varchar(255)
  created_at datetime
}

Table telemetry_service_category {
  id char(36) [primary key]
  name varchar(255)
}

Table telemetry_system {
  id char(36) [primary key]
}

Ref telemetry_service_samples: telemetry_metric_sample.service_id > telemetry_service.id
Ref telemetry_service_system: telemetry_service.system_id > telemetry_system.id
Ref telemetry_service_category: telemetry_service.category_id > telemetry_service_category.id
