Project telemetry_metrics {
  database_type: 'MariaDB'
  Note: 'Telemtry Metrics'
}

Table metric_samples {
  id uuid [primary key]
  service_id uuid
  created_at double
  value double
}

Table services {
  id uuid [primary key]
  system_id uuid
  category_id uuid
  name varchar
  created_at double
}

Table service_categories {
  id uuid [primary key]
  name varchar
}


Table systems {
  id uuid [primary key]
  specs_id uuid
}

Ref service_samples: metric_samples.service_id > services.id 
Ref service_system: systems.id < services.system_id
Ref service_category: services.category_id > service_categories.id
